package com.asjm.fileexplorer.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.asjm.fileexplorer.entity.File;
import com.asjm.fileexplorer.entity.Server;

import com.asjm.fileexplorer.greendao.FileDao;
import com.asjm.fileexplorer.greendao.ServerDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileDaoConfig;
    private final DaoConfig serverDaoConfig;

    private final FileDao fileDao;
    private final ServerDao serverDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileDaoConfig = daoConfigMap.get(FileDao.class).clone();
        fileDaoConfig.initIdentityScope(type);

        serverDaoConfig = daoConfigMap.get(ServerDao.class).clone();
        serverDaoConfig.initIdentityScope(type);

        fileDao = new FileDao(fileDaoConfig, this);
        serverDao = new ServerDao(serverDaoConfig, this);

        registerDao(File.class, fileDao);
        registerDao(Server.class, serverDao);
    }
    
    public void clear() {
        fileDaoConfig.clearIdentityScope();
        serverDaoConfig.clearIdentityScope();
    }

    public FileDao getFileDao() {
        return fileDao;
    }

    public ServerDao getServerDao() {
        return serverDao;
    }

}
